### ISSUE TITLE
"Error: you must be logged in to the server" in tab completion

### ISSUE THREAD

**Issue by phmarek** [rottencandy/vimkubectl#7] opened 2023-11-08 06:42 UTC
If you open `vim` and do `:Kedit <tab>` without being logged in, this text comes up as completion.

**Comment by phmarek** [comment] 2023-11-09 08:08
`NVIM v0.9.4`; `strace` confirms that an error code is returned.

`:set verbose=255 verbosefile=/tmp/....` doesn't work for `Kedit <tab>` completion, though.

```
:echo system("oc project")
:echo v:shell_error
```
correctly gives 1.


8caac6c6332d0164fdca0c82e6532e2cfd9e66bb seems to help, though that's a bit brute-force and might cause other bugs.

**Comment by rottencandy** [comment] 2023-11-10 18:38
Thx for the pointers, I think this wasn't reproducible for me was because of my kubectl version. It seems to silently fail without any message in case of invalid kubeconfig

**Comment by rottencandy** [comment] 2023-11-10 18:40
I used your fix and let the caller handle the shell_error checks, 85a7e04 should fix this

I want to stop using `system()` and switch to async api soon.

**Comment by rottencandy** [comment] 2023-11-20 17:45
Marking this as fixed, but feel free to reopen if issue persists

**Closed by rottencandy** 2023-11-20 17:45 UTC
